import Image from "next/image";
import "./globals.css";
import happyfamily from "@/app/assets/Happy-family.png";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased flex justify-center`}
      >
        <Image className="bg-no-repeat absolute -z-10 w-full" src={happyfamily} width={0} height={0} alt="happy"/>
        {children}
      </body>
    </html>
  );
}
